title: BTech TY
description: Resources and reference materials for third-year BTech Computer Engineering, including assignments and notes.
theme: jekyll-theme-cayman
show_downloads: true
github:
  another_url: http://example.com/download.zip
